-- Tiered gear: general tiered progression items

local Base = require('proloot.lists._base')

return Base.new('tiered', {
    { name='Eternity Binding Glue', count=1 },
    { name='Eternity Book with Missing Pages', count=1 },
    { name='Missing page of Eternity Book No. 12', count=1 },
    { name='Missing page of Eternity Book No. 18', count=1 },
    { name='Missing page of Eternity Book No. 185', count=1 },
    { name='Missing page of Eternity Book No. 22', count=1 },
    { name='Missing page of Eternity Book No. 3', count=1 },
    { name='Missing page of Eternity Book No. 623', count=1 },
    { name='Missing page of Eternity Book No. 652', count=1 },
    { name='Missing page of Eternity Book No. 84', count=1 },
    { name='Torn Page of Mastery Earth', count=1 },
    { name='Torn Page of Mastery Fire', count=1 },
    { name='Torn Page of Mastery Water', count=1 },
    { name='Torn Page of Mastery Wind', count=1 },
    { name='Piece of Underfoot Stone - 1 of 6', count=1 },
    { name='Piece of Underfoot Stone - 2 of 6', count=1 },
    { name='Piece of Underfoot Stone - 3 of 6', count=1 },
    { name='Piece of Underfoot Stone - 4 of 6', count=1 },
    { name='Piece of Underfoot Stone - 5 of 6', count=1 },
    { name='Piece of Underfoot Stone - 6 of 6', count=1 },
    { name='Mastery of Arcana Rune', count=1 },
    { name='Mastery of Body Rune', count=1 },
    { name='MasterY of Mind Rune', count=1 },
    { name='MasterY of Power Rune', count=1 },
    { name='Mastery of Realms Rune', count=1 },
    { name='Mastery of Tactics Rune', count=1 },
    { name='Seal Mastery of All', count=1 },
    { name='Mindset of Tormax', count=1 },
    { name='Sensibility of Keldor', count=1 },
    { name='Viewpoint of the Vindicator', count=1 },
    { name='Stance of the Statue', count=1 },
    { name='Temperament of the Idol', count=1 },
    { name='Attitude of the Avatar', count=1 },
    { name='Mark of Keldovan', count=1 },
    { name='Mark of Jelvan', count=1 },
    { name='Mark of Ture', count=1 },
    { name='Mark of Hanvar', count=1 },
    { name='Mark of Vangl', count=1 },
    { name='Mark of Mata Muram', count=1 },
    { name="The Arbiter's Heart", count=1 },
    { name="Proof of the Progenitor's End", count=1 },
    { name="Proof of Nanzata's Defeat", count=1 },
    { name="Proof of Tukaarak's Defeat", count=1 },
    { name="Proof of Hraashna's Defeat", count=1 },
    { name="Proof of Ventani's Defeat", count=1 },
    { name="Xorbb's Reflective Lens", count=1 },
    { name='Frozen Soul that Gazed at Xorbb', count=1 },
    { name='Testimony of the Lords', count=1 },
    { name="Fragment of Xorbb's Throne", count=1 },
    { name='Lost Crown of Xorbb', count=1 },
    { name='The lost Foci', count=1 },
    { name='Legends Scrap Book', count=1 },
    { name='Legends Blood Book', count=1 },
    { name="Legends Book of Shard's Landing", count=1 },
    { name='Legends Notebook', count=1 },
    { name='Echo of Air', count=1 },
    { name='Shard of Sacred Metal', count=1 },
    { name="Forest Guardian's Sigil", count=1 },
    { name='Ancient Tablet', count=1 },
    { name='Heartstone of Earth', count=1 },
    { name='Tides of Destiny Essence', count=1 },
    { name='Whisper of Stars', count=1 },
    { name='Beast Fang', count=1 },
    { name='Elemental Essence', count=1 },
    { name='Enchanted Wood', count=1 },
    { name='Mystic Water Essence', count=1 },
    { name='Eternal Flame', count=1 },
    { name='Sacred Ore', count=1 },
    { name='Crystal of Unity', count=1 },
    { name='Spirit Flower', count=1 },
    { name='Tome of Secrets', count=1 },
    { name='Charred Broodbone', count=1 },
    { name='Core of Living Abhorrence', count=1 },
    { name='Barbed Sigil of Domination', count=1 },
    { name='Scroll of Merciless Doctrine', count=1 },
    { name='Blasphemous Reliquary', count=1 },
    { name='Heart of Smoldering Ire', count=1 },
    { name='Phylactery of Absolute Loathing', count=1 },
    { name='Focus of Malevolent Will', count=1 },
    { name='Shard of Endless Spite', count=1 },
    { name='Veil of Withering Scorn', count=1 },
})
